### ISSUE TITLE
periodic calculation of how much storage space a user is taking

### ISSUE THREAD

**Issue by ahgentil** [graasp/graasp-file-item#2]
some way of going trough all the fileItems (and s3 file item (?)) and calculating how much space a member is taking.

should this be something separate? it's own plugin? so that it works for both file-item and s3-file-item?
the plugin could take as options the item types to look into and the `size` property in them, and this way it could work for both item types.

**Comment by pyphilia** [comment]
This issue will be handled in this repo https://github.com/graasp/graasp-file-upload-limiter/issues/5
